service: heyy-backend
org: learnuidev
app: heyy-backend

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

functions:
  authorizer:
    handler: functions/authorizer.handler
  hello-world:
    handler: functions/app.handler
    events:
      - http:
          method: "GET"
          cors: true
          path: /hello-world
          authorizer:
            name: authorizer
            type: token
            identitySource: method.request.header.Authorization

plugins:
  - serverless-offline
